name: xmlrpc
version: 2.0.0+1
author: Ariel Barabas <ariel.baras@gmail.com>
description: Useful helper classes for the XML-RPC parsing.
homepage: https://github.com/abarabas/dart-xmlrpc
environment:
  sdk: '>=1.0.0'
documentation: https://github.com/abarabas/dart-xmlrpc
dependencies:
  crypto: '>=0.9.0 <1.0.0'
  intl: '>=0.9.4 <1.0.0'
  xml: '>=2.1.0 <3.0.0'
dev_dependencies:
  http: '>=0.9.2+3 <1.0.0'
  unittest: any
